env:
  DRONE_RPC_SECRET: "super-secret-rpc-key"
  DRONE_SERVER_HOST: "drone-server.drone.svc.cluster.local"
  DRONE_GITHUB_CLIENT_ID: "Ov23lihzi1is7mIEwvEk"
  DRONE_GITHUB_CLIENT_SECRET: "1124672a2fb40b39306035bbaf9ae77aa63ea539"
  DRONE_SERVER_PROTO: http
  DRONE_SERVER_PORT: "80"
  DRONE_USER_CREATE: "username:namth1410,admin:true"
  DRONE_GITHUB_SERVER: "https://github.com"
  DRONE_LOGS_DEBUG: "true"

ingress:
  enabled: false

service:
  port: 80
  type: ClusterIP
