# path: drone/drone-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-server # Giữ tên này vì ứng dụng Drone đang dùng nó
  namespace: drone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi # Dung lượng phải khớp với PV
  storageClassName: local-path # Phải khớp với PV
  # Dòng quan trọng nhất: Yêu cầu đích danh PV đã tạo ở trên
  volumeName: "drone-server-pv"