env:
  DRONE_RPC_HOST: "drone-server.drone.svc.cluster.local"
  DRONE_RPC_PROTO: "http"
  DRONE_RPC_SECRET: "super-secret-rpc-key"
  DRONE_RUNNER_CAPACITY: "2"
  DRONE_RUNNER_NAME: "runner-1"

service:
  type: ClusterIP
