# path: argo-cd/applications/drone-storage.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-storage # Tên application quản lý storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Giữ Application này không bị xóa nhầm
spec:
  project: default

  # Nguồn: Trỏ đến chính repo này, và thư mục con là 'drone'
  source:
    repoURL: https://github.com/namth1410/infra.git # Thay bằng URL repo của bạn
    targetRevision: main
    path: drone/storage # <--- Trỏ tới thư mục chứa drone-pvc.yaml

  # Đích: Namespace nơi PVC sẽ được tạo
  destination:
    server: https://kubernetes.default.svc
    namespace: drone

  syncPolicy:
    automated:
      prune: true # Prune=true ở đây vẫn an toàn vì file PVC đã có Prune=false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true # Tự động tạo namespace 'drone' nếu chưa có