apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/namth1410/infra.git
    targetRevision: main
    path: drone-runner
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: drone
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
