apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-server
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: drone
  source:
      repoURL: https://charts.drone.io
      chart: drone
      targetRevision: 0.6.5
      helm:
        valueFiles:
          - https://raw.githubusercontent.com/namth1410/infra/refs/heads/main/drone/drone-server/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true