apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-storage
  namespace: argocd
spec:
  destination:
    namespace: drone
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/namth1410/infra.git
    targetRevision: main
    path: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
