# path: argo-cd/applications/drone-storage.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/namth1410/infra.git
    targetRevision: main
    path: drone/storage # <--- CHÍNH XÁC, chỉ quản lý PV
  destination:
    server: https://kubernetes.default.svc
    # PV không thuộc namespace nào, nhưng để destination ở đây cũng không sao
    namespace: drone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true