apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-runner-kube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.drone.io
    chart: drone-runner-kube
    targetRevision: 0.1.10 # phiên bản chart, lấy từ ArtifactHub
    helm:
      values: |
        env:
          DRONE_RPC_HOST: drone-server.drone.svc.cluster.local
          DRONE_RPC_SECRET: super-secret-rpc-key
          DRONE_RPC_PROTO: http
        serviceAccount:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: drone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
