apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-runner
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: drone
  source:
    repoURL: https://charts.drone.io
    chart: drone-runner-docker
    targetRevision: 0.7.0
    helm:
      values: |
        env:
          DRONE_RPC_PROTO: http
          DRONE_RPC_HOST: drone.drone.svc.cluster.local
          DRONE_RPC_SECRET: super-secret-rpc-key
          DRONE_RUNNER_CAPACITY: 1
          DRONE_RUNNER_NAME: runner-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
