apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-server
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: drone
  source:
      repoURL: https://github.com/namth1410/infra.git
      targetRevision: main
      path: drone/drone-server
      directory:
        recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true