apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.17.2
    helm:
      values: |
        expose:
          type: ingress
          ingress:
            hosts:
              core: localhost
              notary: localhost
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
            paths:
              core: /harbor
              notary: /harbor/notary
          tls:
            enabled: false
          externalURL: http://localhost:32104

        harborAdminPassword: "01664157092a"

        persistence:
          persistentVolumeClaim:
            registry:
              size: 5Gi
            chartmuseum:
              size: 1Gi
            jobservice:
              size: 1Gi
            database:
              size: 1Gi
            redis:
              size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
