apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.17.2
      helm:
        values: |
          externalURL: https://harbor.namth.online
          expose:
            type: clusterIP
            tls:
              enabled: false

          harborAdminPassword: "01664157092a"

          persistence:
            persistentVolumeClaim:
              registry:
                size: 5Gi
              chartmuseum:
                size: 1Gi
              jobservice:
                size: 1Gi
              database:
                size: 1Gi
              redis:
                size: 1Gi
    - repoURL: https://github.com/namth1410/infra.git
      targetRevision: main
      path: harbor
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
