tunnel: 58c2d850-c1d3-4c31-8954-864c772e37de
credentials-file: /etc/cloudflared/58c2d850-c1d3-4c31-8954-864c772e37de.json

ingress:
  - hostname: drone.namth.online
    service: http://drone-server.drone.svc.cluster.local:80
  - hostname: threads.namth.online
    service: http://threads.threads-dev.svc.cluster.local:70
  - hostname: argocd.namth.online
    service: http://argocd-server.argocd.svc.cluster.local:443
  - service: http_status:404
