apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command:
            - cloudflared
            - tunnel
            - run
            - 58c2d850-c1d3-4c31-8954-864c772e37de
            - --no-autoupdate
            - --credentials-file
            - /etc/cloudflared/58c2d850-c1d3-4c31-8954-864c772e37de.json
          volumeMounts:
            - name: credentials
              mountPath: /etc/cloudflared/
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: cloudflared-credentials
