---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAbx9cPqSEpzsQ45EpMpDlcYlFXa2w5tzONY4bVRBMn6YyCrvSx02uk2W+Wny2j5HkKxK+BpneUNKbpKNrcqtRcLi3LBsrhag9eD8fXIG8eBlr7lnonAYjU8ba7WuMQnXybmA2l/vPpVc+C0cbqaS/YU3wut2H1NFYNshae5cVak/p9ymx2iriV15cZX5DD2hVl8HTVb6QNUw4JdFcoJ+uPS9keMdO2C/EOMhZLuv1SGZVr9QWNny1ztMBk/61PfZ94R5Il4ujvbqgy5yTwV6eki1OSi4L5LVjZAUySDvflwpp3DEDRO890tQEreOEHjR6qw7kozvTzsGYqSorCHqEH76rnQ3rkoMlHNP/HMK/2i+bBqKJtATHeRH+cgiAnHv2tpx5x2PY0kwJkjJD5g91snv9YuUJdRagKY+1P+tD5IUIOIO/0mq+uCH6FYTVu60BXDHb2qmz1uwT0eQ2qcRt733fFkHjPjHEY1GXFZ6S5rZURTLzKyzEdJB71uiZhI8qzXfYM7c+gSoIboh5rzUvm3BYD3ZKGxbpCDpJ5SXirkfmjRwQDB4xE5d/P3WaNcUQjTq/+QIc5r9wVX+HpzOQRZl1c1VZVqsLkQoLjKxYqKsEYEI7JuZR6GtJ9LnC27rb1MmKFgetrSiH5ph4Fm4CpD6euEvf2GbKIxlOpuFXRG9fCSDy9NjttO4PNiv9Dji34VBrJvzK19o0wJTh/fa236/Gz3sjIeVivwbhAg+d/SMHI2qyi0XGg5/kzRvg3WW0rwlkKVM7pt5QQzFAa0C5zWvpMGDoWuekZHibZD+8WNsaa8Ens0K7gsdbgqDL9wxzLQPWBgN9gst2kkhpGkZsI6M+Ao42tA3PfRvc3ycQpMCg5bKKRY8vri5e7Mk7ukPHevtfo+3aCSu2y7WNlUJlXLZuGb/XMroo83g3TT3N0
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflared
