apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: {"AccountTag":"fe9618b5f7e7bdba45d8245ce773f68e","TunnelSecret":"4NX3PRm15wUscbXPGPTY04wwgr+1OCbadvxCgMibilA=","TunnelID":"58c2d850-c1d3-4c31-8954-864c772e37de","Endpoint":""}
